#pragma once

#include <cstdint>
#include <optional>
#include <string>

#include <SQLiteCpp/SQLiteCpp.h>

#include "syrius_orbit/db/Database.hpp"

namespace syrius_orbit {

/// Represents a single VDA5050 event in the append-only event stream.
struct Vda5050Event {
  int64_t id = 0;                     ///< Auto-generated by SQLite.
  std::string topic;                  ///< VDA5050 topic name.
  std::string item_id;                ///< Entity key for projection GROUP BY.
  std::string received_at;            ///< ISO-8601 daemon receive time.
  std::string manufacturer;           ///< From MQTT topic path.
  std::string serial_number;          ///< From MQTT topic path.
  std::string robot_id;               ///< "{manufacturer}.{serialNumber}".
  std::string direction;              ///< "uplink" or "downlink".
  std::optional<int64_t> header_id;           ///< VDA5050 header ID.
  std::optional<std::string> header_version;  ///< VDA5050 protocol version.
  std::optional<std::string> header_timestamp;///< Original message timestamp.
  std::string payload;                ///< Full VDA5050 message as JSON.
};

/// Repository for the append-only vda5050_events table (write model).
class Vda5050EventsRepository {
 public:
  explicit Vda5050EventsRepository(Database& db);

  /// Inserts a new event. Returns the auto-generated row id.
  /// Throws on failure.
  int64_t insert(const Vda5050Event& event);

  /// Returns the latest event per item_id for the given topic.
  /// Used by the projection layer.
  std::vector<Vda5050Event> findLatestByTopic(const std::string& topic);

 private:
  static Vda5050Event fromRow(const SQLite::Statement& stmt);
  SQLite::Database& db_;
};

}  // namespace syrius_orbit