# migrations.cmake
#
# Generates the embedded migrations header at configure time from
# .sql files in src/db/migrations/. Sets ${MIGRATION_GENERATED_SOURCES}
# which should be added to the target's source list.

set(_migrations_dir "${CMAKE_SOURCE_DIR}/src/db/migrations")
set(_generated_dir "${CMAKE_CURRENT_BINARY_DIR}/generated")
set(_generated_header "${_generated_dir}/syrius_orbit/migrations_generated.h")

file(MAKE_DIRECTORY "${_generated_dir}/syrius_orbit")

# Collect and sort .sql files.
file(GLOB _sql_files CONFIGURE_DEPENDS "${_migrations_dir}/*.sql")
list(SORT _sql_files)

list(LENGTH _sql_files _count)
if(_count EQUAL 0)
    message(FATAL_ERROR "No .sql migration files found in ${_migrations_dir}")
endif()

# Write header prologue.
file(WRITE "${_generated_header}"
    "// Auto-generated by cmake/migrations.cmake -- DO NOT EDIT.\n"
    "#pragma once\n"
    "#include <array>\n"
    "#include \"syrius_orbit/SchemaMigrator.hpp\"\n"
    "namespace syrius_orbit {\n"
    "inline constexpr std::array<Migration, ${_count}> EMBEDDED_MIGRATIONS = {{\n"
)

# Embed each .sql file as a raw string literal entry.
foreach(_f ${_sql_files})
    get_filename_component(_filename "${_f}" NAME)
    string(SUBSTRING "${_filename}" 0 3 _version)
    string(REGEX REPLACE "^([0-9]+)_(.+)\\.sql$" "\\2" _name "${_filename}")

    if("${_version}" STREQUAL "" OR "${_name}" STREQUAL "")
        message(FATAL_ERROR "Invalid migration filename: ${_filename} "
                "(expected NNN_name.sql)")
    endif()

    file(READ "${_f}" _sql_content)
    file(APPEND "${_generated_header}" "    {\"${_version}\", \"${_name}\", R\"SQL(\n")
    file(APPEND "${_generated_header}" "${_sql_content}")
    file(APPEND "${_generated_header}" ")SQL\"},\n")
endforeach()

# Write header epilogue.
file(APPEND "${_generated_header}"
    "}};\n"
    "}  // namespace syrius_orbit\n"
)

include_directories(${_generated_dir})

set(MIGRATION_GENERATED_SOURCES ${_generated_header})

message(STATUS "Generated migrations header: ${_generated_header} (${_count} migrations)")
